### ISSUE TITLE
Add a pushing step to TF Serving Image howto

### ISSUE THREAD

**Issue by sayakpaul** [sayakpaul/deploy-hf-tf-vision-models#17]
I think it'd make sense to also add a step that tells you about how to push the image to a container registry here: `hf_vision_model_tfserving_gke/HOW-TO-BUILD-TFServing.md`.

**Comment by deep-diver** [comment]
I have written a simple [codelab](https://gde-codelabs.github.io/posts/how-to-build-cpuopt-tfserving/#0) about this. Maybe we can refer to this? (of course, the sentences should be revised a bit)

Think this as a draft

**Comment by sayakpaul** [comment]
Sure.
