### ISSUE TITLE
Deployment with Kubernetes

### ISSUE THREAD

**Issue by sayakpaul** [sayakpaul/deploy-hf-tf-vision-models#4]

**Comment by deep-diver** [comment]
I am not sure yet if I can deploy a model for prediction using the optimized TensorFlow runtime(TFRT) even though the doc says it is almost identical to TFServing in the perspective of technical setups. 

What I am not sure is that if the optimized TFRT is only supported in Vertex AI. Maybe need to experiment, or if you @sayakpaul have found any documents for this, please let me know.

**Comment by sayakpaul** [comment]
I don't think the Kubernetes way of deployment would support it.
