### ISSUE TITLE
methodology to load-test on GKE

### ISSUE THREAD

**Issue by deep-diver** [sayakpaul/deploy-hf-tf-vision-models#7]
This issue is to brainstorm how to perform load-test the TF Serving deployed on GKE.

To start, I think it is good to choose over spec/configs of VM, TFServing itself, and batch inference. For instance:
- number of pods(nodes): 1, 2, 4, 8, ...
- number of vCPU: 16
- RAM Capacity: 64GB
- TFServing
  - `intra_op_parallelism_threads`: equals to the `number of vCPU`
  - `inter_op_parallelism_threads`: really high number (128) -> ... -> 4
- batch inference
  - `max_batch_size`: really high number (1024) -> ... -> 16
  - `batch_timeout_micros`: 1000000 (1 second) -> 100000 -> ... -> 10
  - `num_batch_threads`: equals to the `number of vCPU`
  - `max_enqueued_batches`: really high number (128) -> ... -> equals to the `num_batch_threads`

We can gradually reduce the spec of VM and values of each configurations, then we can figure out which one is optimal. 

The values above are chosen randomly without any solid principle. Some of them are referenced from [this official doc](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/batching/README.md#batch-scheduling-parameters-and-tuning) though.

**Comment by sayakpaul** [comment]
> inter_op_parallelism_threads: really high number (128) -> ... -> 4

128 seems like a surprisingly large number to me :o Won't we need 128 vCPU machine for that? 

I think we should also try other machine types this time that come with AVX512 support with VNNI: n2 and c2.

I will let you lead this effort and I will of course, share the workload.

**Comment by deep-diver** [comment]
> 128 seems like a surprisingly large number to me :o Won't we need 128 vCPU machine for that?

to be clear, `intra_op_parallelism_threads` is usually set to the number of cores. I am not sure what would be right number for `inter_op_parallelism_threads`, so I just wanted to explore from 128. Of course, we can discuss about this 

> I think we should also try other machine types this time that come with AVX512 support with VNNI: n2 and c2.

Great suggestion 👍🏼

**Comment by deep-diver** [comment]
one nice thing to note (FYI)
: https://github.com/GoogleCloudPlatform/distributed-load-testing-using-kubernetes

we can run Locust on GKE for distributed load testing. In this way, we can simulate more realistic situations like multiple users from multiple sources try to reach the TFServing endpoint.

**Comment by sayakpaul** [comment]
> one nice thing to note (FYI) : https://github.com/GoogleCloudPlatform/distributed-load-testing-using-kubernetes
> 
> we can run Locust on GKE for distributed load testing. In this way, we can simulate more realistic situations like multiple users from multiple sources try to reach the TFServing endpoint.

There's actually a blog post about it too: https://cloud.google.com/architecture/load-testing-and-monitoring-aiplatform-models#prepare_the_resnet_model_for_deployment. We can follow this for load-testing discarding the monitoring aspect. WDYT?

> to be clear, intra_op_parallelism_threads is usually set to the number of cores. I am not sure what would be right number for inter_op_parallelism_threads, so I just wanted to explore from 128. Of course, we can discuss about this

No I mean if the machine itself doesn't have that many core (128), I don't think setting `inter` to 128 would make any sense. But please correct me if I am wrong.

**Comment by sayakpaul** [comment]
Closing it as we have incorporated Locust local support.
